### ISSUE TITLE
Confine to view instead of modal

### ISSUE THREAD

**Issue by sonaye** [alexbrillant/react-native-expanding-circle-transition#1]
Nice component! I am planning to use it in my current project.

At the moment the transition is forced on the whole screen, I think the component would be more practical if it was confined only to it's parent view. For example: when you have a tab bar at the bottom, you don't want the animation to go over it. Furthermore, this enable animations that go beyond transitioning from one screen to screen, a box with some words in it for example. I believe the modification here is simple, using a view instead of a modal (the view can be hidden as well).

Another point, why not add a prop to feed the modal (or it's replacement) with some content (children), and a flag to keep it visible after the animation, say `keepVisible`, this way the component can be used for prompt actions or messages, extending its capabilities even more.

I actually worked on the code a little, but then I stopped and though that I should share here first. Thanks for the great work.

**Comment by alexbrillant** [comment]
Hello @sonaye! Thanks for the feedback. I think this is a great idea. I sent you a collaboration invite. You can submit a pull request if you like. I will work on this tomorrow.

**Comment by sonaye** [comment]
awesome! i'll see what i can do

**Comment by alexbrillant** [comment]
@sonaye What about using an absolutely positioned view to mask the part of the screen that should not be affected by the transition?

**Comment by alexbrillant** [comment]
I cannot find a solution for this issue. Have you tried anything?

**Comment by alexbrillant** [comment]
@sonaye I don't know how to implement this. All the positions would need to be absolute for this to work ? How can I mask the parts that the animation should not go over ? If you have any ideal please tell me. Thanks

**Comment by sonaye** [comment]
@alexbrillant not really, i don't think absolute positioning would be needed, i think what you are looking for is z-index maybe? i am planning to work on a pr soon, hopefully in the next couple of days it will be ready and we can further discuss the mechanism of which we can implement this.

**Comment by alexbrillant** [comment]
I got it. It's working. We can add a prop called zIndex and remove the modal like you said(only keep the animated view). The animated view should be absolutely positioned do because otherwise it impacts the other views while animating. Also, maybe we could add a modal boolean prop so that the user can decide if he wants it over everything. Tell me what you think. I can code it myself but it is your ideal so I can let you do it if you want. Thanks !

**Comment by alexbrillant** [comment]
@sonaye  I added a zIndex prop in 1.1.7 ! It allows to control what goes over it. I haven't added the children prop yet.

**Comment by alexbrillant** [comment]
I don't plan on adding a children prop.

**Comment by sonaye** [comment]
I think z-index does the trick, although it's a little bit of work to change all the elements in a view to have a proper z-index, this makes the component lees easier to use, but it works, hence, to need for a children prop.

i think the size of the area of which the animation expands to should be controlled though, say that you wish the expansion to happen in half of the screen for example, or under the nav bar only, something like that.

**Comment by sonaye** [comment]
I couldn't however test the new feature properly. here is how the animation works out of the box without touching any elements in the view:

![kapture 2017-02-19 at 8 26 11](https://cloud.githubusercontent.com/assets/23000873/23099684/fe669d78-f67d-11e6-84b9-18266c4d7b88.gif)

Notice how touchables and tab bars by default have a higher z-index value (> 100).

But when changing the z-index of only the text label under the nav bar for example, the animation breaks down:

![kapture 2017-02-19 at 8 27 38](https://cloud.githubusercontent.com/assets/23000873/23099685/fe6c0696-f67d-11e6-9c08-31fce45fc8f7.gif)

How did you test this? do you have any working code where you specify certain z-indexs for the animation and for other elements in a view?

**Comment by alexbrillant** [comment]
@sonaye I didn't experience any issue myself: 
https://gist.github.com/alexbrillant/847d9b8d960fc41dc64ab183ece5ec88
I think the default value should be higher thanks for pointing that out. 

Can you send me the relevant code so I can help/reproduce if there really is an issue?

**Comment by sonaye** [comment]
Oh, i think i didn't point out what i was trying to achieve correctly form the beginning, i am trying to have the transition animate behind the components not in front of them, that's why i proposed having a children prop in the first place, does this make sense? so, the "Circle Transition" text and the tab bar are working properly in my example. I'll test your code, and see what can I share with you to reproduce the issue.

**Comment by sonaye** [comment]
When assigning zIndex = 101 for the text with a random key value as shown in my example (under job details), the animation fails.

**Comment by sonaye** [comment]
I am not getting any animation with your exact code. what rn version are you using, ios or android? can you provide a gif?

**Comment by alexbrillant** [comment]
![animation](https://cloud.githubusercontent.com/assets/19400226/23101410/e94494f8-f660-11e6-96b6-7975ac5abfc8.gif)

**Comment by sonaye** [comment]
1.1.7?

![kapture 2017-02-19 at 13 04 44](https://cloud.githubusercontent.com/assets/23000873/23101413/07973e5e-f6a4-11e6-89ef-b788b111b3a1.gif)

**Comment by alexbrillant** [comment]
Make sure you import the package and not the file directly. 
`import CircleTransition from 'react-native-expanding-circle-transition'`

**Comment by sonaye** [comment]
i did that yeah, perhaps you didn't push some latest modifications that you have made on the code? strange that we are not getting the same result.

**Comment by alexbrillant** [comment]
No I am using the package itself now and it is still working. 
Here is the update gist(that imports the package react-native-expanding-circle-transition 1.1.7: 
https://gist.github.com/alexbrillant/847d9b8d960fc41dc64ab183ece5ec88

**Comment by alexbrillant** [comment]
What is your version of react native?
Here is mine : 
```
➜  Exemples react-native -v
react-native-cli: 2.0.1
react-native: 0.41.2
```

**Comment by sonaye** [comment]
same here, this very odd, i'll dig deeper and come back when i find something.

**Comment by alexbrillant** [comment]
@sonaye  I am removing this feature. It broke my package on multiple device. I don't understand why
